org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = io.github.lwozr
mod_id = buildhelper_litematica
mod_name = Build Helper for Litematica
author = LwozR
mod_file_name = buildhelper-litematica-fabric

mod_version = 1.0.0

minecraft_version_out = 26.1.2
minecraft_version = 26.1.2

fabric_loader_version = 0.19.5
mod_menu_version = 20.0.2

malilib_dependency = maven.modrinth:malilib:FItuNokS
litematica_dependency = maven.modrinth:litematica:w8P6TokG

minecraft_range = >=26.1 <26.2
malilib_range = >=0.28.12
litematica_range = >=0.27.14
